stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  tags:
    - csl
    - docker
  image: python
  before_script:
    - pip install -r ./src/backend/requirements.txt
  script:
    - python test/test.py 2>&1 | tee results.log
    - python test/test_admin.py 2>&1 | tee -a results.log
  artifacts:
    untracked: true
    when: on_success
    expire_in: 30 days
    paths:
      - results.log

lint-test-job:
  stage: test
  tags:
    - csl
    - docker
  image: python
  before_script:
    - pip install flake8 pylint
    - pip install -r ./src/backend/requirements.txt
  script:
    - flake8 src/backend --max-line-length=120 --ignore=E402,E126,E122,E261,W293
    - pylint src/backend --errors-only

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
